version: "3.7"

services: 
    database:
        image: postgres
        container_name: database_rentalx
        restart: always
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentalx
        volumes: 
            - pgdata:/data/postgres
        
    app: 
        build: .
        container_name: rentalx
        restart: always
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/app
        links:
            - database
        depends_on: 
            - database

volumes: 
    pgdata:
        driver: local